/*
# Push reminders for the home-screen app

- push_subscriptions: each device that turned on notifications (Web Push
  endpoint + keys). Private — only the push edge function reads or writes it.
- push_config: the app's VAPID key pair, generated by the push function the
  first time it runs. Private — no policies, so only the service role can read it.
- reminders: notifications the app has planned (morning briefing, proffer
  window, assignment and confirm-by reminders). The app plans the next 7 days
  whenever it's opened; the push function sends each one when it's due and
  stamps sent_at so nothing goes out twice.
- reminder_settings: one row — on/off switches and the morning time.
- A pg_cron job calls the push function every minute to send what's due.

Single-tenant RLS (anon, USING true) on reminders and reminder_settings,
matching every other table in this app.
*/

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  endpoint text UNIQUE NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  user_agent text,
  created_at timestamptz NOT NULL DEFAULT now(),
  last_success_at timestamptz,
  last_error text
);
ALTER TABLE push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS push_config (
  id int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  public_key text NOT NULL,
  private_key text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE push_config ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS reminders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key text UNIQUE NOT NULL,
  send_at timestamptz NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  url text,
  kind text,
  sent_at timestamptz,
  status text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS reminders_due_idx ON reminders (send_at) WHERE sent_at IS NULL;
ALTER TABLE reminders ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_reminders" ON reminders;
CREATE POLICY "anon_select_reminders" ON reminders FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_insert_reminders" ON reminders;
CREATE POLICY "anon_insert_reminders" ON reminders FOR INSERT TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_update_reminders" ON reminders;
CREATE POLICY "anon_update_reminders" ON reminders FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_delete_reminders" ON reminders;
CREATE POLICY "anon_delete_reminders" ON reminders FOR DELETE TO anon, authenticated USING (true);

CREATE TABLE IF NOT EXISTS reminder_settings (
  id int PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  enabled boolean NOT NULL DEFAULT true,
  morning boolean NOT NULL DEFAULT true,
  morning_time text NOT NULL DEFAULT '06:00',
  reserve boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE reminder_settings ENABLE ROW LEVEL SECURITY;
INSERT INTO reminder_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "anon_select_reminder_settings" ON reminder_settings;
CREATE POLICY "anon_select_reminder_settings" ON reminder_settings FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_update_reminder_settings" ON reminder_settings;
CREATE POLICY "anon_update_reminder_settings" ON reminder_settings FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_insert_reminder_settings" ON reminder_settings;
CREATE POLICY "anon_insert_reminder_settings" ON reminder_settings FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Send due reminders every minute.
CREATE EXTENSION IF NOT EXISTS pg_cron;
CREATE EXTENSION IF NOT EXISTS pg_net;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = 'push-send-due') THEN
    PERFORM cron.unschedule('push-send-due');
  END IF;
END $$;

SELECT cron.schedule(
  'push-send-due',
  '* * * * *',
  $cron$
  SELECT net.http_post(
    url := 'https://pgjdhdsgciflvwbqtcjm.supabase.co/functions/v1/push',
    headers := '{"Content-Type": "application/json"}'::jsonb,
    body := '{"action": "send-due"}'::jsonb
  );
  $cron$
);
